#!/bin/sh
set -eu

app_root="/Library/Application Support/Geer/app"
runtime_root="$app_root/runtime/geer"

export GEER_WORKSPACE="$app_root"
export GEER_HOME="${GEER_HOME:-$HOME/.geer}"
export GEER_CLI="/usr/local/bin/geer"
export GEER_PI_LAUNCHER="/usr/local/bin/geer-pi"

exec "$runtime_root/geer" "$@"
